# Generated by Django 6.0.3 on 2026-05-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encadrant_nom', models.CharField(help_text="Utilisé si l'encadrant n'a pas de compte utilisateur.", max_length=250, verbose_name="Nom de l'encadrant")),
                ('role', models.CharField(blank=True, default='Encadrant académique', max_length=100, verbose_name='Rôle')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Encadrement',
                'verbose_name_plural': 'Encadrements',
                'ordering': ['-date_debut'],
            },
        ),
    ]
