# Generated by Django 6.0.3 on 2026-05-12 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encadrement', '0001_initial'),
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encadrement',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encadrements', to=settings.AUTH_USER_MODEL, verbose_name='Encadrant (utilisateur)'),
        ),
        migrations.AddField(
            model_name='encadrement',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements', to='etudiants.stage', verbose_name='Stage'),
        ),
    ]
