# Generated by Django 6.0.3 on 2026-05-20 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encadrement', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(default='À compléter', max_length=200, verbose_name='Département')),
                ('specialite', models.CharField(default='À compléter', max_length=200, verbose_name='Spécialité')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie / Présentation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadrant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Encadrant',
                'verbose_name_plural': 'Encadrants',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
