# Generated by Django 6.0.3 on 2026-05-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='etudiants.stage', verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_evaluation'],
            },
        ),
    ]
