# Generated by Django 6.0.3 on 2026-05-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name='Titre')),
                ('fichier', models.FileField(upload_to='rapports/', verbose_name='Fichier')),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='etudiants.stage', verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_depot'],
            },
        ),
    ]
