# Generated by Django 6.0.3 on 2026-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('STUDENT', 'Étudiant'), ('SUPERVISOR', 'Encadrant'), ('COMPANY', 'Entreprise')], default='STUDENT', max_length=20, verbose_name='Rôle'),
        ),
    ]
