# Generated by Django 6.0.3 on 2026-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Étudiant'), ('SUPERVISOR', 'Encadrant'), ('COMPANY', 'Entreprise')], default='STUDENT', max_length=20, verbose_name='Rôle'),
        ),
    ]
